**Exploratory Data Analysis 2**

**1. Data Exploration and Preprocessing:**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [3]:
from google.colab import files
files = files.upload()

Saving adult_with_headers.csv to adult_with_headers (1).csv

In [4]:
df = pd.read_csv('adult_with_headers.csv')
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [5]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
df.tail()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [7]:
df.shape

(32561, 15)

In [8]:
df.size

488415

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [10]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [11]:
# Basic data exploration
print("Summary Statistics:\n", df.describe())
print("Missing Values:\n", df.isnull().sum())
print("Data Types:\n", df.dtypes)

Summary Statistics:
                 age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000

       hours_per_week
count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
Missing Values:
 age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64
Data Types:
 age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [12]:
# Convert the "workclass" column from string to float
df['workclass'] = df['workclass'].astype('category').cat.codes

In [13]:
# Convert the "education" column from string to float
df['education'] = df['education'].astype('category').cat.codes

In [14]:
# Convert the "Maritual_ststus" column from string to float
df['marital_status'] = df['marital_status'].astype('category').cat.codes

In [15]:
# Convert the "occupation" column from string to float
df['occupation'] = df['occupation'].astype('category').cat.codes

In [16]:
# Convert the "relationship" column from string to float
df['relationship'] = df['relationship'].astype('category').cat.codes

In [17]:
# Convert the "race" column from string to float
df['race'] = df['race'].astype('category').cat.codes

In [18]:
# Convert the "sex" column from string to float
df['sex'] = df['sex'].astype('category').cat.codes

In [19]:
# Convert the "native_country" column from string to float
df['native_country'] = df['native_country'].astype('category').cat.codes

In [20]:
# Convert the "income" column from string to float
df['income'] = df['income'].astype('category').cat.codes
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,4,257302,7,12,2,13,5,4,0,0,0,38,39,0
32557,40,4,154374,11,9,2,7,0,4,1,0,0,40,39,1
32558,58,4,151910,11,9,6,1,4,4,0,0,0,40,39,0
32559,22,4,201490,11,9,4,1,3,4,1,0,0,20,39,0
32560,52,5,287927,11,9,2,4,5,4,0,15024,0,40,39,1

In [21]:
# Handle missing values (example: filling missing values with median for numerical and mode for categorical)
df.fillna(df.median(), inplace=True)
for column in df.select_dtypes(include=['object']).columns:
    df[column].fillna(df[column].mode()[0], inplace=True)

In [22]:
# Apply scaling techniques
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns

In [23]:
# Standard Scaling
scaler = StandardScaler()
df_standard_scaled = df.copy()
df_standard_scaled[numerical_features] = scaler.fit_transform(df_standard_scaled[numerical_features])

In [24]:
# Min-Max Scaling
scaler = MinMaxScaler()
df_minmax_scaled = df.copy()
df_minmax_scaled[numerical_features] = scaler.fit_transform(df_minmax_scaled[numerical_features])

In [25]:
# Print the scaled data for comparison
print("Standard Scaled Data:\n", df_standard_scaled.head())
print("Min-Max Scaled Data:\n", df_minmax_scaled.head())

Standard Scaled Data:
         age  workclass    fnlwgt  education  education_num  marital_status  \
0  0.030671          7 -1.063611          9       1.134739               4
1  0.837109          6 -1.008707          9       1.134739               2
2 -0.042642          4  0.245079         11      -0.420060               0
3  1.057047          4  0.425801          1      -1.197459               2
4 -0.775768          4  1.408176          9       1.134739               2

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1      0.148453      -0.21666
1           4             0     4    1     -0.145920      -0.21666
2           6             1     4    1     -0.145920      -0.21666
3           6             0     2    1     -0.145920      -0.21666
4          10             5     2    0     -0.145920      -0.21666

   hours_per_week  native_country  income
0       -0.035429              39       0
1       -2.222153              39       0
2       -0.035429              39       0
3       -0.035429              39       0
4       -0.035429               5       0
Min-Max Scaled Data:
         age  workclass    fnlwgt  education  education_num  marital_status  \
0  0.301370          7  0.044302          9       0.800000               4
1  0.452055          6  0.048238          9       0.800000               2
2  0.287671          4  0.138113         11       0.533333               0
3  0.493151          4  0.151068          1       0.400000               2
4  0.150685          4  0.221488          9       0.800000               2

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1       0.02174           0.0
1           4             0     4    1       0.00000           0.0
2           6             1     4    1       0.00000           0.0
3           6             0     2    1       0.00000           0.0
4          10             5     2    0       0.00000           0.0

   hours_per_week  native_country  income
0        0.397959              39       0
1        0.122449              39       0
2        0.397959              39       0
3        0.397959              39       0
4        0.397959               5       0

In [27]:
# Discuss scaling preferences
scaling_preference = """
Standard Scaling is preferred when the data follows a Gaussian distribution and we want to center the data around zero with a unit variance.
Min-Max Scaling is preferred when we want to scale the data within a specific range (usually 0 to 1) which is useful for algorithms that do not assume any distribution (e.g., Neural Networks).
"""
print(scaling_preference)

Standard Scaling is preferred when the data follows a Gaussian distribution and we want to center the data around zero with a unit variance.
Min-Max Scaling is preferred when we want to scale the data within a specific range (usually 0 to 1) which is useful for algorithms that do not assume any distribution (e.g., Neural Networks).

**2. Encoding Techniques:**

In [28]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [29]:
# One-Hot Encoding for categorical variables with less than 5 categories
categorical_features_onehot = [col for col in df.select_dtypes(include=['object']).columns if df[col].nunique() < 5]
df_onehot_encoded = pd.get_dummies(df, columns=categorical_features_onehot)

In [30]:
# Label Encoding for categorical variables with more than 5 categories
categorical_features_label = [col for col in df.select_dtypes(include=['object']).columns if df[col].nunique() >= 5]
label_encoder = LabelEncoder()

for col in categorical_features_label:
    df[col] = label_encoder.fit_transform(df[col])

In [31]:
# Print the encoded data
print("One-Hot Encoded Data:\n", df_onehot_encoded.head())
print("Label Encoded Data:\n", df.head())

One-Hot Encoded Data:
    age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          7   77516          9             13               4
1   50          6   83311          9             13               2
2   38          4  215646         11              9               0
3   53          4  234721          1              7               2
4   28          4  338409          9             13               2

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1          2174             0
1           4             0     4    1             0             0
2           6             1     4    1             0             0
3           6             0     2    1             0             0
4          10             5     2    0             0             0

   hours_per_week  native_country  income
0              40              39       0
1              13              39       0
2              40              39       0
3              40              39       0
4              40               5       0
Label Encoded Data:
    age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          7   77516          9             13               4
1   50          6   83311          9             13               2
2   38          4  215646         11              9               0
3   53          4  234721          1              7               2
4   28          4  338409          9             13               2

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1          2174             0
1           4             0     4    1             0             0
2           6             1     4    1             0             0
3           6             0     2    1             0             0
4          10             5     2    0             0             0

   hours_per_week  native_country  income
0              40              39       0
1              13              39       0
2              40              39       0
3              40              39       0
4              40               5       0

In [32]:
# Discuss pros and cons of encoding techniques
encoding_discussion = """
Pros of One-Hot Encoding:
- Does not assume any ordinal relationship between categories.
- Widely accepted and used in various ML algorithms.

Cons of One-Hot Encoding:
- Increases dimensionality, leading to sparse matrices.

Pros of Label Encoding:
- Simple and easy to implement.
- Does not increase dimensionality.

Cons of Label Encoding:
- Assumes ordinal relationships which might not exist, leading to potential model bias.
"""
print(encoding_discussion)

Pros of One-Hot Encoding:
- Does not assume any ordinal relationship between categories.
- Widely accepted and used in various ML algorithms.

Cons of One-Hot Encoding:
- Increases dimensionality, leading to sparse matrices.

Pros of Label Encoding:
- Simple and easy to implement.
- Does not increase dimensionality.

Cons of Label Encoding:
- Assumes ordinal relationships which might not exist, leading to potential model bias.

**3. Feature Engineering:**

In [33]:
# Create new features (examples)
df['age_group'] = pd.cut(df['age'], bins=[0, 30, 50, 100], labels=['young', 'middle_aged', 'senior'])
df['capital_diff'] = df['capital_gain'] - df['capital_loss']

In [34]:
# Apply log transformation to skewed numerical feature
df['capital_gain_log'] = np.log1p(df['capital_gain'])  # log1p is used to handle log(0)

In [35]:
# Rationale for new features
feature_engineering_rationale = """
New Feature 'age_group': Categorizes individuals into 'young', 'middle_aged', and 'senior' groups to capture age-related patterns.
New Feature 'capital_diff': Computes the difference between capital gain and capital loss to better understand the net capital effect.
Log Transformation on 'capital_gain': Log transformation is applied to handle the right skewness in 'capital_gain' which can improve model performance.
"""
print(feature_engineering_rationale)

New Feature 'age_group': Categorizes individuals into 'young', 'middle_aged', and 'senior' groups to capture age-related patterns.
New Feature 'capital_diff': Computes the difference between capital gain and capital loss to better understand the net capital effect.
Log Transformation on 'capital_gain': Log transformation is applied to handle the right skewness in 'capital_gain' which can improve model performance.

In [36]:
# Print the transformed data
print("Data with New Features and Log Transformation:\n", df.head())

Data with New Features and Log Transformation:
    age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          7   77516          9             13               4
1   50          6   83311          9             13               2
2   38          4  215646         11              9               0
3   53          4  234721          1              7               2
4   28          4  338409          9             13               2

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1          2174             0
1           4             0     4    1             0             0
2           6             1     4    1             0             0
3           6             0     2    1             0             0
4          10             5     2    0             0             0

   hours_per_week  native_country  income    age_group  capital_diff  \
0              40              39       0  middle_aged          2174
1              13              39       0  middle_aged             0
2              40              39       0  middle_aged             0
3              40              39       0       senior             0
4              40               5       0        young             0

   capital_gain_log
0          7.684784
1          0.000000
2          0.000000
3          0.000000
4          0.000000

**4. Feature Selection**

In [37]:
!pip install ppscore

Requirement already satisfied: ppscore in /usr/local/lib/python3.10/dist-packages (1.3.0)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ppscore) (1.5.3)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /usr/local/lib/python3.10/dist-packages (from ppscore) (1.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.16.0)

In [38]:
from sklearn.ensemble import IsolationForest
import ppscore as pps

In [39]:
# Isolation Forest for outlier detection
iso_forest = IsolationForest(contamination=0.1)
outliers = iso_forest.fit_predict(df.select_dtypes(include=['int64', 'float64']))

In [40]:
# Remove outliers
df_no_outliers = df[outliers != -1]

In [41]:
# PPS score analysis
pps_matrix = pps.matrix(df_no_outliers).pivot(columns='x', index='y', values='ppscore')
correlation_matrix = df_no_outliers.corr()

<ipython-input-41-5c915cb369a0>:3: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = df_no_outliers.corr()

In [42]:
# Print PPS matrix and correlation matrix
print("PPS Matrix:\n", pps_matrix)
print("Correlation Matrix:\n", correlation_matrix)

PPS Matrix:
 x                      age  age_group  capital_diff  capital_gain  \
y
age               1.000000   0.603721      0.000000      0.000000
age_group         1.000000   1.000000      0.000000      0.000000
capital_diff      0.000000   0.000000      1.000000      0.700833
capital_gain      0.000000   0.000000      0.996562      1.000000
capital_gain_log  0.000000   0.000000      0.999343      0.999343
capital_loss      0.000000   0.000000      0.990332      0.000000
education         0.000000   0.000000      0.000000      0.000000
education_num     0.000000   0.000000      0.000000      0.000000
fnlwgt            0.000000   0.000000      0.000000      0.000000
hours_per_week    0.000000   0.000000      0.000000      0.000000
income            0.000000   0.000000      0.000000      0.000000
marital_status    0.164759   0.117472      0.000000      0.000000
native_country    0.000000   0.000000      0.000000      0.000000
occupation        0.000000   0.000047      0.000000      0.000000
race              0.000000   0.000000      0.000000      0.000000
relationship      0.009436   0.000000      0.000000      0.000000
sex               0.000000   0.000000      0.000000      0.000000
workclass         0.000000   0.000000      0.000000      0.000000

x                 capital_gain_log  capital_loss  education  education_num  \
y
age                       0.000000           0.0   0.017419       0.017419
age_group                 0.000000           0.0   0.113127       0.113127
capital_diff              0.700833           0.0   0.000000       0.000000
capital_gain              0.996562           0.0   0.000000       0.000000
capital_gain_log          1.000000           0.0   0.000000       0.000000
capital_loss              0.000000           1.0   0.000000       0.000000
education                 0.000000           0.0   1.000000       1.000000
education_num             0.000000           0.0   1.000000       1.000000
fnlwgt                    0.000000           0.0   0.000000       0.000000
hours_per_week            0.000000           0.0   0.000000       0.000000
income                    0.000000           0.0   0.000000       0.000000
marital_status            0.000000           0.0   0.000000       0.000000
native_country            0.000000           0.0   0.000000       0.000000
occupation                0.000000           0.0   0.019740       0.019740
race                      0.000000           0.0   0.000000       0.000000
relationship              0.000000           0.0   0.000000       0.000000
sex                       0.000000           0.0   0.000000       0.000000
workclass                 0.000000           0.0   0.000000       0.000000

x                   fnlwgt  hours_per_week    income  marital_status  \
y
age               0.000000        0.000000  0.023141        0.210693
age_group         0.119817        0.109055  0.000000        0.372550
capital_diff      0.000000        0.000000  0.000000        0.000000
capital_gain      0.000000        0.000000  0.000000        0.000000
capital_gain_log  0.000000        0.000000  0.000000        0.000000
capital_loss      0.000000        0.000000  0.000000        0.000000
education         0.000000        0.000000  0.000000        0.000000
education_num     0.000000        0.000000  0.017790        0.000000
fnlwgt            1.000000        0.000000  0.000000        0.000000
hours_per_week    0.000000        1.000000  0.000000        0.000000
income            0.000000        0.000000  1.000000        0.000000
marital_status    0.000000        0.000000  0.000000        1.000000
native_country    0.000000        0.000000  0.000000        0.000000
occupation        0.000000        0.005138  0.000000        0.001017
race              0.000000        0.000000  0.000000        0.000000
relationship      0.000000        0.000000  0.000000        0.132917
sex               0.000000        0.000000  0.000000        0.000000
workclass         0.000000        0.000000  0.000000        0.000000

x                 native_country  occupation      race  relationship  \
y
age                      0.00000    0.009219  0.000000      0.149283
age_group                0.00000    0.117900  0.000000      0.238378
capital_diff             0.00000    0.000000  0.000000      0.000000
capital_gain             0.00000    0.000000  0.000000      0.000000
capital_gain_log         0.00000    0.000000  0.000000      0.000000
capital_loss             0.00000    0.000000  0.000000      0.000000
education                0.00000    0.000000  0.000000      0.000000
education_num            0.00564    0.153647  0.000000      0.000000
fnlwgt                   0.00000    0.000000  0.003409      0.000000
hours_per_week           0.00000    0.000000  0.000000      0.000000
income                   0.00000    0.000000  0.000000      0.000000
marital_status           0.00000    0.000000  0.000000      0.303848
native_country           1.00000    0.000000  0.000000      0.000000
occupation               0.00000    1.000000  0.000000      0.000000
race                     0.00000    0.000000  1.000000      0.000000
relationship             0.00000    0.000000  0.000000      1.000000
sex                      0.00000    0.000000  0.000000      0.227483
workclass                0.00000    0.203981  0.000000      0.000000

x                      sex  workclass
y
age               0.000000   0.019742
age_group         0.000000   0.000000
capital_diff      0.000000   0.000000
capital_gain      0.000000   0.000000
capital_gain_log  0.000000   0.000000
capital_loss      0.000000   0.000000
education         0.000000   0.000000
education_num     0.000000   0.000000
fnlwgt            0.000000   0.000000
hours_per_week    0.000000   0.000000
income            0.000000   0.000000
marital_status    0.000000   0.000000
native_country    0.000000   0.000000
occupation        0.000000   0.119241
race              0.000000   0.000000
relationship      0.129332   0.000000
sex               1.000000   0.000000
workclass         0.000000   1.000000
Correlation Matrix:
                        age  workclass    fnlwgt  education  education_num  \
age               1.000000   0.010825 -0.077753  -0.011715       0.020846
workclass         0.010825   1.000000 -0.016166   0.019000       0.046102
fnlwgt           -0.077753  -0.016166  1.000000  -0.025123      -0.044326
education        -0.011715   0.019000 -0.025123   1.000000       0.360639
education_num     0.020846   0.046102 -0.044326   0.360639       1.000000
marital_status   -0.283084  -0.059469  0.027274  -0.033963      -0.052972
occupation       -0.016634   0.252708 -0.002969  -0.027024       0.100268
relationship     -0.260693  -0.092565  0.008563  -0.008751      -0.079984
race              0.020161   0.049690 -0.023889   0.011995       0.027494
sex               0.077836   0.091755  0.029520  -0.031500      -0.003221
capital_gain      0.018152   0.004686 -0.012641   0.017951       0.025791
capital_loss     -0.000752  -0.008193 -0.016372   0.042413       0.007471
hours_per_week    0.090471   0.130465 -0.019534   0.053930       0.128413
native_country    0.000553  -0.003113 -0.056753   0.065317       0.053852
income            0.215909   0.036052 -0.012517   0.070774       0.286160
capital_diff      0.017677   0.006587 -0.008036   0.006565       0.022956
capital_gain_log  0.013576   0.004321 -0.015170   0.017039       0.021065

                  marital_status  occupation  relationship      race  \
age                    -0.283084   -0.016634     -0.260693  0.020161
workclass              -0.059469    0.252708     -0.092565  0.049690
fnlwgt                  0.027274   -0.002969      0.008563 -0.023889
education              -0.033963   -0.027024     -0.008751  0.011995
education_num          -0.052972    0.100268     -0.079984  0.027494
marital_status          1.000000   -0.004863      0.183826 -0.067188
occupation             -0.004863    1.000000     -0.076040  0.007474
relationship            0.183826   -0.076040      1.000000 -0.116936
race                   -0.067188    0.007474     -0.116936  1.000000
sex                    -0.117955    0.082264     -0.569243  0.089245
capital_gain           -0.032969    0.012183     -0.029377  0.016944
capital_loss           -0.021644    0.001433     -0.009447  0.007079
hours_per_week         -0.192997    0.072330     -0.246775  0.042408
native_country         -0.024020   -0.012032     -0.004073  0.130612
income                 -0.185756    0.068784     -0.234800  0.069201
capital_diff           -0.026285    0.011374     -0.025911  0.014532
capital_gain_log       -0.024344    0.008768     -0.018069  0.014015

                       sex  capital_gain  capital_loss  hours_per_week  \
age               0.077836      0.018152     -0.000752        0.090471
workclass         0.091755      0.004686     -0.008193        0.130465
fnlwgt            0.029520     -0.012641     -0.016372       -0.019534
education        -0.031500      0.017951      0.042413        0.053930
education_num    -0.003221      0.025791      0.007471        0.128413
marital_status   -0.117955     -0.032969     -0.021644       -0.192997
occupation        0.082264      0.012183      0.001433        0.072330
relationship     -0.569243     -0.029377     -0.009447       -0.246775
race              0.089245      0.016944      0.007079        0.042408
sex               1.000000      0.024863      0.008247        0.226555
capital_gain      0.024863      1.000000     -0.016361        0.017441
capital_loss      0.008247     -0.016361      1.000000        0.005481
hours_per_week    0.226555      0.017441      0.005481        1.000000
native_country   -0.008947      0.010695      0.001332        0.000876
income            0.200394      0.047178      0.029967        0.209912
capital_diff      0.021866      0.967487     -0.268716        0.015415
capital_gain_log  0.017219      0.950343     -0.017587        0.010228

                  native_country    income  capital_diff  capital_gain_log
age                     0.000553  0.215909      0.017677          0.013576
workclass              -0.003113  0.036052      0.006587          0.004321
fnlwgt                 -0.056753 -0.012517     -0.008036         -0.015170
education               0.065317  0.070774      0.006565          0.017039
education_num           0.053852  0.286160      0.022956          0.021065
marital_status         -0.024020 -0.185756     -0.026285         -0.024344
occupation             -0.012032  0.068784      0.011374          0.008768
relationship           -0.004073 -0.234800     -0.025911         -0.018069
race                    0.130612  0.069201      0.014532          0.014015
sex                    -0.008947  0.200394      0.021866          0.017219
capital_gain            0.010695  0.047178      0.967487          0.950343
capital_loss            0.001332  0.029967     -0.268716         -0.017587
hours_per_week          0.000876  0.209912      0.015415          0.010228
native_country          1.000000  0.017620      0.009966          0.008155
income                  0.017620  1.000000      0.037868          0.026071
capital_diff            0.009966  0.037868      1.000000          0.919960
capital_gain_log        0.008155  0.026071      0.919960          1.000000

In [43]:
# Discuss the impact of outliers and PPS vs Correlation
feature_selection_discussion = """
Outliers can negatively affect model performance by skewing the data distribution and leading to biased predictions.
PPS (Predictive Power Score) measures the predictive power of one feature on another, capturing both linear and non-linear relationships.
Correlation matrix measures linear relationships between features, which might miss out on important non-linear associations captured by PPS.
"""
print(feature_selection_discussion)

Outliers can negatively affect model performance by skewing the data distribution and leading to biased predictions.
PPS (Predictive Power Score) measures the predictive power of one feature on another, capturing both linear and non-linear relationships.
Correlation matrix measures linear relationships between features, which might miss out on important non-linear associations captured by PPS.